### ISSUE TITLE
stack overflow running `git stack`

### ISSUE THREAD

**Issue by kaspar030** [epage/git-stack#90]
### 

- [X] I have searched the [discussions](https://github.com/epage/git-stack/discussions)
- [X] I have searched the existing issues

### Description

I just installed `git-stack` using `cargo install --locked` on an up-to-date Arch linux installation.

Then, running `git-stack` leads to some 40 sec of 100% CPU usage, `git-stack` then stack overflows.

### Version

git-stack 0.2.9

### Steps to reproduce

This was on my local clone of kaspar030/RIOT, which has a lot of branches.
I just typed `git-stack` there.

How can I provide more context?

### Actual Behaviour

```
riot on  master via ⍱ 
❯ git-stack

thread 'main' has overflowed its stack
fatal runtime error: stack overflow
Aborted (core dumped)
riot on  master via ⍱ took 41s 
❯
```

### Expected Behaviour

I don't know the expected output.

### Debug Output

https://gist.github.com/kaspar030/b2e524241f7403abc2864181421d94cc

**Comment by epage** [comment]
Ouch, hadn't tested on a big repo yet and I can see that happening.  This uses recursion a lot.

As a workaround setting [stack.stack to descendants](https://github.com/epage/git-stack/blob/main/docs/reference.md#config-fields) will probably avoid the worse problems.

I might be able to insert some hacks to workaround this but I'm looking at a more fundamental change in our data structure that makes it easier to iterate rather than recurse.
